### PR TITLE
Adding moderation guidelines to slack intro

### PR DESCRIPTION
**Pull request by sugaroverflow**
Adding some text to link to the Moderation guidelines as requested in issue #108

### CODE REVIEW

**Comment by sugaroverflow** [comment]
@AlannaBurke please review - maybe the text needs rewording and then assign to @drnikki for merge :)

**Review by AlannaBurke — APPROVED** [review]
Looks good to me!

**Comment by sugaroverflow** [comment]
@drnikki merge please :)

**Comment by drnikko** [comment]
<3

**Pull request merged**
